{% set name = "lightly-train" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lightly_train-{{ version }}.tar.gz
  sha256: 8b775c25d7f1d0d1e2f4e1d41de9c8dfa9e946fcfb6f2f8443dc65dae64ec17c

build:
  entry_points:
    - lightly-train = lightly_train._cli:_cli_entrypoint
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - albumentations >=1.3.1,!=1.4.18,!=1.4.19,!=1.4.20,!=1.4.21,!=1.4.22
    - eval-type-backport >=0.2
    - filelock >=3.0.0
    - lightly >=1.5.20
    - omegaconf >=2.3
    - psutil >=5.0
    - pyarrow >=15.0.0
    - pytorch-lightning >=2.1
    - tensorboard >=2.10.0
    - pytorch >=2.1.0,<2.6
    - torchmetrics >=0.8
    - torchvision >=0.16.0
    - transformers >=4.46
    - tqdm >=4.0.0

test:
  imports:
    - lightly_train
  commands:
    - pip check
    - lightly-train --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lightly-ai/lightly-train
  summary: Train models with self-supervised learning in a single command
  description: LightlyTrain is the first PyTorch framework to pretrain computer vision models on unlabeled data for industrial applications
  license: AGPL-3.0-only AND AGPL-3.0-or-later
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - giswqs
